{% set name = "flake8-docstrings" %}
{% set version = "1.4.0" %}
{% set sha256 = "9c0db5a79a1affd70fdf53b8765c8a26bf968e59e0252d7f2fc546b41c0cda06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pydocstyle >=2.1
    - flake8
    - flake8-polyfill

test:
  commands:
    - "flake8 --version | grep flake8-docstrings:"

about:
  home: https://gitlab.com/pycqa/flake8-docstrings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Extension for flake8 which uses pydocstyle to check docstrings'
  dev_url: https://gitlab.com/pycqa/flake8-docstrings

extra:
  recipe-maintainers:
    - dopplershift
