{% set name = "flake8-docstrings" %}
{% set version = "1.1.0" %}
{% set sha256 = "0d2a7c12e57db7bef56f820d0294bed7a577a18609246f70d223bc1bdccc185c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pydocstyle >=2.0
    - flake8
    - flake8-polyfill

test:
  commands:
    - "flake8 --version | grep flake8-docstrings:"

about:
  home: https://gitlab.com/pycqa/flake8-docstrings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Extension for flake8 which uses pydocstyle to check docstrings'
  dev_url: https://gitlab.com/pycqa/flake8-docstrings

extra:
  recipe-maintainers:
    - dopplershift
