travis:
  secure:
    BINSTAR_TOKEN: V1LjP3uigjjhjsu7hZw4Pfn3cfsFS0yuvBRvZ2tcAaL4uKXfR9nfZyflvlNS6KpA9Ajgt3k6RExmfNCxmZsUmTJ8LlxRadg2tIhdJbxwU/8Unvlbsxwmkds74Uk4zwzmQkFykManJzaDm7HZdLBXvh97WzNjEs7qOnIr9ZYSBwGU6nQYX+XZ1r0dNHWbTVPQbNacAkQZ7W0WCq5QkxhxggHRnkG3IzoCgqx16cMkYtHnOaAlfbuBh+W9ssJMzDCOydy7DU/8UV+JtU1L0z/7P6c5eUkpr8hS4JGL5qN9ZDlKnuRB/DmqoTGxlNHNiaOY3WmfPtsb40lLuhimV89YBXsEx+crp18nJpPavz6uLl+xUFDFXIpg59TZeouNHMnp/Ui1MTK7eaIG6NhEepNFGVH4peWGeIK1CSvHSWKZv5PBdDPwuhmgRzmi0Yd1SmoxvuWVmuJa6zXzEK0mg6xPYZkfL2E7sWbBsm9+9Y+cfOz6iy9Kklf+WYo+d6mvY8VuH/2sAJWPpOg/+8MprHLq593kDmgfTlV7Suqoau/o3/ECtLRa+4igUA/Y2/bpwH03naJHEqfogNln+VT8pXJTFFddn6RCN62xJLlRsQeMwrtsYtAvJw453qCSRBqH/5iUj6kgzQr9NLhOXDLP2baSyFCjbes/2uBi2sMlzBfCKCM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
