travis:
  secure:
    BINSTAR_TOKEN: jFPZIhfy4CH9pwaN+VhIBCSocj/3qga0IbiRwAriOGJBX8tIR7aPGSZwyTO4tS7T2PmWrffDMNVPU/tv5FLIARjAB1QWqH8B5F7rQ1JAcjeVqbuq7AQPlym1K8GrRM6IP6KJWA4L5rmCHD0cj/WV0POS57r/12PyDk6O9wERqijplMGtCk3FFJ4aWbrxX71phEhGphV7NGHxlVsA2f9e+nXQlDClxRTjQCcQ3jBcE8o6KU1KibQkmq2GI8nh3nx1bwQi9TzphCdK15Vq2b6/JjpxBfXBK2htPTrov215Qd8ITEqRUC8vSI/esfI0fel2I3jm0+VyRFgCm+H92WLvVmqlcKwwtMiEVF8Y1XhWLiz0Hi/+634GmlK4N1LNqSuK4nWQooymwdk1sz+jOC9H1LDutPlXFCJwKB/XirKqtAwVwT8GlujuWkvGnrk8ggMQrbMDR+8qNqnAgBfwV0hlsECstJ8fevqmut0TUFjmA3ZfSk7OuCUMkXd5sX5edlylhd4GSYb50yddtFTqGAdx5aADbAgxCf9nMkKvz2xl0V4wl/z2t1wjxAnjCxijOpmNlXi6euCst6uOUOy0SHM+LZmBuP2gvqexRQzVgJG0zNULjMeTHC0+s7y9YFfrpL9XczmTg6WALkqZJ9WHlfFRRsuhNjsSJ6Xs27UrhamQf5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
