travis:
  secure:
    BINSTAR_TOKEN: mb5U61Z91HX6ZZcCrBdYKp5+l+I6slhvFgAI5HVMG2PsbqHCKHX+v/F+iXEm6L7n4aZfINjjoprkQC4+H1hiT0NkH/W9W8M9J5f4Of6Ts77oqqVCeycqTsrIuWKWLAmr7dn3jCAlZSWy97eMn5QcgZC+JqFwzqEUBg1a743UcO6PIrDyqWUKBRSq3wxmqE5MqM1NYWhcAzVItf1bqM+v3zTGULuMvu3hjKyVhnp5b/h3qX4cpPKdnZm9COqcUokFdBaVbRDzRWYP2c73ZCu39kY+Fca/08/2ZcirqlTfm9nFuZa/dyVW9iq8EmzJtXl/2Gi4OIJtEcsn59Cyo07KKoLYWhknM2IrMaZHbM/+63euDrELdjfjIfUXYwVWMUVB/R7pqXu/Ic16Aqos1H9hZPpm2mpMh2VYM3aY9/hjA0GXqqtrNukry5x3VR5MZeokzHb4pEXFexjS1WK041D/K+7JXqyNqgDejzHQiUd+thFC3in3k8jc0piml1E6NBq5hTm8QLpYY3EPHmI++QzZcVNZ6J4oFdO4UugiVGv8pvYHD1QWix0cCgwdCNh9zxOoL5Ot/UzOJKpaYiteTbvKa9EhjbvqOj6o3goBgnrsX2ac3SyiWKbhQGMsB28ZSeJMZ5QRFvAx38wQdtcxcgFgrFn7gsBY3qsnOnOArSWubTU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
